FROM tensorflow/tensorflow

RUN apt-get -y update
RUN apt-get -y upgrade

RUN apt-get -y install git nano wget curl gnupg

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list

RUN apt-get update

RUN apt-get -y install edgetpu-compiler
RUN python3 -m pip install --upgrade pip
RUN apt-get install libgl1 libglib2.0-0
RUN pip install onnx onnxruntime onnxsim onnx-tf torch pandas torchvision opencv-python tqdm matplotlib seaborn scipy tensorflow_probability tensorflow
