FROM "tensorflow/tensorflow"

WORKDIR /home

RUN apt-get -y update

RUN apt-get -y install git usbutils nano

RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-get -y update
RUN apt-get install -y libedgetpu1-std

RUN python3 -m pip install --upgrade pip

RUN apt-get install -y python3-pycoral

RUN mkdir coral && cd coral

RUN apt-get install git

RUN git clone https://github.com/CuzImClicks/pycoral ./pycoral # cannot copy -> $'\r': command not found
RUN cd pycoral
WORKDIR pycoral
COPY pull.sh .
COPY push.sh .
COPY Logger.py ./examples
RUN bash examples/install_requirements.sh detect_image.py
RUN mkdir input
RUN mkdir output
