FROM tensorflow/tensorflow

WORKDIR /home

RUN apt-get -y update
RUN apt-get -y upgrade

RUN apt-get -y install git usbutils nano wget unzip

RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-get -y update
RUN apt-get install -y libedgetpu1-std

RUN python3 -m pip install --upgrade pip

RUN apt-get install -y python3-pycoral

RUN mkdir coral && cd coral

COPY repo/tensorflow-2.12.0-cp38-cp38-linux_x86_64.whl .
RUN python -m pip install tensorflow-2.12.0-cp38-cp38-linux_x86_64.whl

RUN git clone https://github.com/CuzImClicks/Raccoon # cannot copy -> $'\r': command not found
RUN cd /home/Raccoon
RUN git submodule update --init # download CuzImClicks/pycoral
WORKDIR /home/Raccoon/pycoral
RUN cd /home/Raccoon/pycoral
RUN git submodule update --init # download CuzImClicks/models
COPY pull.py .
COPY push.py .
RUN bash examples/install_requirements.sh detect_image.py
RUN mkdir input
RUN mkdir output
RUN apt-get -y update
RUN apt-get -y upgrade
